//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECQ_Soft.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ECQ_Soft.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///    {
        ///  &quot;type&quot;: &quot;service_account&quot;,
        ///  &quot;project_id&quot;: &quot;grounded-atrium-467409-e7&quot;,
        ///  &quot;private_key_id&quot;: &quot;98928bc2c7041ffbdb0b372c6952461c21e11423&quot;,
        ///  &quot;private_key&quot;: &quot;-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC6uEx3M68W3hB5\nVIea4XalMA/UQw896q9kNr2clDz1tnpkT/6yU1xbhK2AGky7X+fGf4KShvzr7UCs\nWQd/AE1S66sqQcvxzaEBYZbbJoQKSjptqrhLvJFoPomHRPNJVLAmfba3DXUeyOw8\noBU82/kP/S8a3wwZFg/Z/taK8s/J0hTP1p1KKpDTqNje1K4GeFSMzXqvyXlFE0HK\nhYYtW7LIpWdlKxhfR8fpqVewkI5bUpAdagh1DuQVQtFqK+gwLlT [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GoogleCredentialJson1 {
            get {
                return ResourceManager.GetString("GoogleCredentialJson1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///    {
        ///  &quot;type&quot;: &quot;service_account&quot;,
        ///  &quot;project_id&quot;: &quot;lateral-origin-489215-c6&quot;,
        ///  &quot;private_key_id&quot;: &quot;ded47593e3f817529e7018c93521f7e492f4ea71&quot;,
        ///  &quot;private_key&quot;: &quot;-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCu39Zjd++gfa1I\noElukhjrCJh+u6CIf/D2WfkftJ1CZUnP6RPRRirZhUNTilZVwRLkt1qT1cwRHKMz\n9i77ZO+C12U71YPBWshulOXitr2p+w9VgBxXGFAElhLu2WGYUXOPfJfd/fdddnYR\nMyrNXvLfxVKlsInzsQtcJfbgD17wry+7/o72wZQiZnOqaHoSAcYSzeBiapgCJNNk\nMDaEf54jNHRXZ4ePe0N1OJ4Uc6tC/zYsX5JqlzJ59n3/Oq2i/phg [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GoogleCredentialJson2 {
            get {
                return ResourceManager.GetString("GoogleCredentialJson2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hideEye {
            get {
                object obj = ResourceManager.GetObject("hideEye", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Loading_icon {
            get {
                object obj = ResourceManager.GetObject("Loading_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap showEye {
            get {
                object obj = ResourceManager.GetObject("showEye", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap snapedit_1757909053744 {
            get {
                object obj = ResourceManager.GetObject("snapedit_1757909053744", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap userimage {
            get {
                object obj = ResourceManager.GetObject("userimage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap VneccoLogo {
            get {
                object obj = ResourceManager.GetObject("VneccoLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
